### ISSUE TITLE
perovskite data loader issue

### ISSUE THREAD

**Issue by yuanqidu** [deepchem/moleculenet#30]
I found the following errors while loading the perovskite dataset.

job exception: local variable 'X_shape' referenced before assignment

  0%|                                                                  | 0/16 [01:14<?, ?trial/s, best loss=?]
Traceback (most recent call last):
  File "fingerprint.py", line 204, in <module>
    val_metrics, test_metrics = bayesian_optimization(args)
  File "fingerprint.py", line 137, in bayesian_optimization
    max_evals=args['num_trials'])
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/hyperopt/fmin.py", line 553, in fmin
    rval.exhaust()
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/hyperopt/fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/hyperopt/fmin.py", line 292, in run
    self.serial_evaluate()
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/hyperopt/fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/hyperopt/base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  File "fingerprint.py", line 120, in objective
    val_metrics, test_metrics = main(save_path, configure, hyperparams)
  File "fingerprint.py", line 49, in main
    args, tasks, all_dataset, transformers = load_dataset(args)
  File "/home/v-yuanqidu/moleculenet/examples/utils.py", line 105, in load_dataset
    featurizer=featurizer, splitter=splitter, reload=False)
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/deepchem/molnet/load_function/material_datasets/load_perovskite.py", line 107, in load_perovskite
    return loader.load_dataset('perovskite', reload)
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/deepchem/molnet/load_function/molnet_loader.py", line 201, in load_dataset
    train = transformer.transform(train)
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/deepchem/trans/transformers.py", line 197, in transform
    _, y_shape, w_shape, _ = dataset.get_shape()
  File "/home/v-yuanqidu/.conda/envs/deepchem/lib/python3.7/site-packages/deepchem/data/datasets.py", line 2557, in get_shape
    return tuple(X_shape), tuple(y_shape), tuple(w_shape), tuple(ids_shape)
UnboundLocalError: local variable 'X_shape' referenced before assignment

**Comment by yuanqidu** [comment]
mp_formation_energy dataset has the similar issue.
